// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: minekube/connect/v1alpha1/watch_service.proto

package connectv1alpha1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sending this message rejects a session proposed by the WatchService. This message should be sent to inform
	// the WatchService that the server will not try to make a take the proposed session. The only purpose of
	// this message is to provide quicker feedback to the player that he will not be connected with an optional
	// localized reason. See https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto.
	// If the session is not rejected the watcher should establish the connection for the proposed session.
	// If neither of these actions happen the proposal times out out and the player receives a connection timeout
	// error indicating that the endpoint is currently unavailable.
	SessionRejection *SessionRejection `protobuf:"bytes,1,opt,name=session_rejection,json=sessionRejection,proto3" json:"session_rejection,omitempty"`
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetSessionRejection() *SessionRejection {
	if x != nil {
		return x.SessionRejection
	}
	return nil
}

type WatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The proposed session that intents to connect.
	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type SessionRejection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the proposed session.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The optional reason why the proposed session was rejected.
	// To specify a user facing localized message refer to
	// https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto
	Reason *status.Status `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *SessionRejection) Reset() {
	*x = SessionRejection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRejection) ProtoMessage() {}

func (x *SessionRejection) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRejection.ProtoReflect.Descriptor instead.
func (*SessionRejection) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRejection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionRejection) GetReason() *status.Status {
	if x != nil {
		return x.Reason
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique session id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The address of the TunnelService to establish the player connection.
	// This allows to establish a direct connection to the TunnelService
	// that hosts the player connection and maintain the lowest latency.
	TunnelServiceAddr string `protobuf:"bytes,2,opt,name=tunnel_service_addr,json=tunnelServiceAddr,proto3" json:"tunnel_service_addr,omitempty"`
	// The player of this session that will be connected.
	//
	// Note that only the profile name might be available if auth.passthrough is enabled
	// since the username is sent by the player initially (https://wiki.vg/Protocol#Login_Start).
	Player *Player `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	// The authentication termination of the session connection.
	// See Authentication for more documentation.
	Auth *Authentication `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTunnelServiceAddr() string {
	if x != nil {
		return x.TunnelServiceAddr
	}
	return ""
}

func (x *Session) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *Session) GetAuth() *Authentication {
	if x != nil {
		return x.Auth
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The profile of the player.
	Profile *GameProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// The optional IP address of the player.
	// This field may be empty or is a fake address
	// generated for this particular player.
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetProfile() *GameProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Player) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type GameProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The Minecraft UUID of the player.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The Minecraft name of the player.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The profile properties that may contain skin data and more.
	Properties []*GameProfileProperty `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
}

func (x *GameProfile) Reset() {
	*x = GameProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameProfile) ProtoMessage() {}

func (x *GameProfile) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameProfile.ProtoReflect.Descriptor instead.
func (*GameProfile) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{5}
}

func (x *GameProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameProfile) GetProperties() []*GameProfileProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type GameProfileProperty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of this property.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The value of this property
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The signature of this property.
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *GameProfileProperty) Reset() {
	*x = GameProfileProperty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameProfileProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameProfileProperty) ProtoMessage() {}

func (x *GameProfileProperty) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameProfileProperty.ProtoReflect.Descriptor instead.
func (*GameProfileProperty) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{6}
}

func (x *GameProfileProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameProfileProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GameProfileProperty) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// The authentication details of a session specifies how the connecting player is authenticated.
//
// The Minecraft account of every session is authenticated using an external auth service that can confirm
// a connecting player is who he claims he is.
//
// The official Minecraft session server (https://wiki.vg/Protocol_Encryption#Authentication)
// is the most commonly used API to authenticate online mode players with a real Minecraft account.
type Authentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether authentication is terminated by the TunnelService or the client that calls the TunnelService.
	// A TunnelService client can be the Minecraft server that receives the player connection.
	//
	// True means a player connection is in login state and has not yet received the encryption request packet.
	// Whether and how the authentication is done is the responsibility of the target Minecraft server that
	// establishes the tunnel to the TunnelService to receive the connecting player.
	// Players with a pass-through session cannot be rerouted to another server by the TunnelService,
	// but only by the server that established the tunnel because the connection might be encrypted and not
	// readable by the TunnelService.
	//
	// False means a player authentication is offloaded externally (e.g. by the TunnelService that sends the
	// player connection) and is not done by the Minecraft server that establishes the tunnel to the TunnelService.
	// Players without a pass-through session can be rerouted to another server by the TunnelService as well as
	// by the server that established the tunnel.
	//
	//
	// Summary of Pros and Cons:
	//
	// passthrough=false
	//  + Maximum flexibility: TunnelService can route players between servers on demand
	//  + Maximum feature support: TunnelService can fully engage with the player (e.g. send messages)
	//  - Less authenticity: player authentication is offloaded to the trusted TunnelService
	//  - Less security: TunnelService has full control over the connection io
	//
	// passthrough=true
	//  + Maximum authenticity: player authentication is done locally by the TunnelService client
	//  + Maximum security: TunnelService cannot spy on the encrypted player connection
	//  - Less flexibility: TunnelService cannot route a player connection to a different server
	//  - Less features available: TunnelService only acts as a lightweight reverse proxy with limited features
	//
	//
	// It is a security/authenticity decision whether to accept sessions in non-passthrough
	// mode if you cannot trust that the TunnelService the player connection origins from.
	//
	// This model compares best with a https://en.wikipedia.org/wiki/TLS_termination_proxy.
	Passthrough bool `protobuf:"varint,1,opt,name=passthrough,proto3" json:"passthrough,omitempty"`
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP(), []int{7}
}

func (x *Authentication) GetPassthrough() bool {
	if x != nil {
		return x.Passthrough
	}
	return false
}

var File_minekube_connect_v1alpha1_watch_service_proto protoreflect.FileDescriptor

var file_minekube_connect_v1alpha1_watch_service_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x77, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x19, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x58, 0x0a, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a,
	0x0d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x10,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xc3, 0x01, 0x0a,
	0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x6b,
	0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x22, 0x5e, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x22, 0x81, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x69, 0x6e,
	0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x13, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x32, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x74,
	0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x61,
	0x73, 0x73, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x32, 0x6e, 0x0a, 0x0c, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x05, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x27, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6d, 0x69,
	0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x86, 0x02, 0x0a, 0x1d, 0x63, 0x6f,
	0x6d, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42, 0x11, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x4e,
	0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xa2, 0x02,
	0x03, 0x4d, 0x43, 0x58, 0xaa, 0x02, 0x19, 0x4d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0xca, 0x02, 0x19, 0x4d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x5c, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xe2, 0x02, 0x25, 0x4d,
	0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x5c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5c,
	0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x1b, 0x4d, 0x69, 0x6e, 0x65, 0x6b, 0x75, 0x62, 0x65, 0x3a,
	0x3a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_minekube_connect_v1alpha1_watch_service_proto_rawDescOnce sync.Once
	file_minekube_connect_v1alpha1_watch_service_proto_rawDescData = file_minekube_connect_v1alpha1_watch_service_proto_rawDesc
)

func file_minekube_connect_v1alpha1_watch_service_proto_rawDescGZIP() []byte {
	file_minekube_connect_v1alpha1_watch_service_proto_rawDescOnce.Do(func() {
		file_minekube_connect_v1alpha1_watch_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_minekube_connect_v1alpha1_watch_service_proto_rawDescData)
	})
	return file_minekube_connect_v1alpha1_watch_service_proto_rawDescData
}

var file_minekube_connect_v1alpha1_watch_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_minekube_connect_v1alpha1_watch_service_proto_goTypes = []interface{}{
	(*WatchRequest)(nil),        // 0: minekube.connect.v1alpha1.WatchRequest
	(*WatchResponse)(nil),       // 1: minekube.connect.v1alpha1.WatchResponse
	(*SessionRejection)(nil),    // 2: minekube.connect.v1alpha1.SessionRejection
	(*Session)(nil),             // 3: minekube.connect.v1alpha1.Session
	(*Player)(nil),              // 4: minekube.connect.v1alpha1.Player
	(*GameProfile)(nil),         // 5: minekube.connect.v1alpha1.GameProfile
	(*GameProfileProperty)(nil), // 6: minekube.connect.v1alpha1.GameProfileProperty
	(*Authentication)(nil),      // 7: minekube.connect.v1alpha1.Authentication
	(*status.Status)(nil),       // 8: google.rpc.Status
}
var file_minekube_connect_v1alpha1_watch_service_proto_depIdxs = []int32{
	2, // 0: minekube.connect.v1alpha1.WatchRequest.session_rejection:type_name -> minekube.connect.v1alpha1.SessionRejection
	3, // 1: minekube.connect.v1alpha1.WatchResponse.session:type_name -> minekube.connect.v1alpha1.Session
	8, // 2: minekube.connect.v1alpha1.SessionRejection.reason:type_name -> google.rpc.Status
	4, // 3: minekube.connect.v1alpha1.Session.player:type_name -> minekube.connect.v1alpha1.Player
	7, // 4: minekube.connect.v1alpha1.Session.auth:type_name -> minekube.connect.v1alpha1.Authentication
	5, // 5: minekube.connect.v1alpha1.Player.profile:type_name -> minekube.connect.v1alpha1.GameProfile
	6, // 6: minekube.connect.v1alpha1.GameProfile.properties:type_name -> minekube.connect.v1alpha1.GameProfileProperty
	0, // 7: minekube.connect.v1alpha1.WatchService.Watch:input_type -> minekube.connect.v1alpha1.WatchRequest
	1, // 8: minekube.connect.v1alpha1.WatchService.Watch:output_type -> minekube.connect.v1alpha1.WatchResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_minekube_connect_v1alpha1_watch_service_proto_init() }
func file_minekube_connect_v1alpha1_watch_service_proto_init() {
	if File_minekube_connect_v1alpha1_watch_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRejection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameProfileProperty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minekube_connect_v1alpha1_watch_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_minekube_connect_v1alpha1_watch_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minekube_connect_v1alpha1_watch_service_proto_goTypes,
		DependencyIndexes: file_minekube_connect_v1alpha1_watch_service_proto_depIdxs,
		MessageInfos:      file_minekube_connect_v1alpha1_watch_service_proto_msgTypes,
	}.Build()
	File_minekube_connect_v1alpha1_watch_service_proto = out.File
	file_minekube_connect_v1alpha1_watch_service_proto_rawDesc = nil
	file_minekube_connect_v1alpha1_watch_service_proto_goTypes = nil
	file_minekube_connect_v1alpha1_watch_service_proto_depIdxs = nil
}
